[REF] odoo110_py37: Add odoo cron service separated - vx#45773
Odoo using workers has a limit-timeout-real affecting the cron ones
So, the current solution is increasing the timeout

The first solution was using:
 - limit_time_real_cron=0

But it raised the following error:

    2021-03-25 15:28:49,497 47 ERROR DB odoo.service.server: Worker (47) Exception occured, exiting...
    Traceback (most recent call last):
    File "/home/odoo/instance/odoo/odoo/service/server.py", line 843, in run
        t.join()
    File "/usr/share/pyenv/versions/3.7.10/lib/python3.7/threading.py", line 1044, in join
        self._wait_for_tstate_lock()
    File "/usr/share/pyenv/versions/3.7.10/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
        elif lock.acquire(block, timeout):
    File "/home/odoo/instance/odoo/odoo/service/server.py", line 771, in signal_time_expired_handler
        raise Exception('CPU time limit exceeded.')
            Exception: CPU time limit exceeded.

So, it is not working as expected

A second option could be increasing the following parameters:

    limit_time_cpu
    limit_time_real

But it affects the real users timeout and the workers could be used for a long time
And the instance go down.

Another solution is avoid making crons spending a long time but it will a hard work

Another solution is deploying manually but we need to avoid that as possible